### ISSUE TITLE
Lean data instructors should use a format that's readable on github

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/lean-data-practices#1]
To view the docx document, I have to download the binary, and then hopefully I have a program which can view it. Since it's just text, Markdown would be a better format so that people can read it straight on github.

**Comment by nukeador** [comment]
Also open formats would be nice to have, like a simple PDF instead of proprietary Office formats :)

**Comment by jishnu** [comment]
Proposed a markdown copy of the file which feels like a good solution. 

As background, we originally chose docx because we thought it would be easier to share/print those between multiple job functions, is importable into online tools like GDocs and non-complex docx files have some support in LibreOffice and OpenOffice.

**Comment by mikehenrty** [comment]
looking good, thanks!
